# Generated by Django 5.2.17 on 2026-10-05 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0003_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundamental', models.CharField(choices=[('SERVE', 'Servizio'), ('RECEPTION', 'Ricezione'), ('SET', 'Alzata'), ('ATTACK', 'Attacco'), ('BLOCK', 'Muro'), ('DEFENSE', 'Difesa'), ('GENERAL', 'Generale')], max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('POINT', 'Punto'), ('OK', 'Ok'), ('ERROR', 'Errore')], max_length=10, null=True)),
                ('quality', models.CharField(blank=True, choices=[('#', '#'), ('+', '+'), ('!', '!'), ('-', '-'), ('=', '=')], max_length=1, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touches', to='scout.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touches', to='scout.player')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touches', to='scout.set')),
            ],
        ),
    ]
