# Generated by Django 5.2.17 on 2026-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0004_touch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touch',
            name='quality',
            field=models.CharField(blank=True, choices=[('#', '#'), ('+', '+'), ('!', '!'), ('/', '/'), ('-', '-'), ('=', '=')], max_length=1, null=True),
        ),
    ]
