# Generated by Django 5.2.17 on 2026-10-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0005_alter_touch_quality'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='set',
            constraint=models.UniqueConstraint(fields=('match', 'number'), name='unique_set_per_match'),
        ),
    ]
