# Generated by Django 5.2.17 on 2026-10-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0006_set_unique_set_per_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='opponent_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='our_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='serving_team',
            field=models.CharField(choices=[('OUR', 'Noi'), ('OPPONENT', 'Avversari')], default='OUR', max_length=10),
            preserve_default=False,
        ),
    ]
