# Generated by Django 5.2.17 on 2026-10-07 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0007_set_opponent_score_set_our_score_set_serving_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineups_position_1', to='scout.player')),
                ('position_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineups_position_2', to='scout.player')),
                ('position_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineups_position_3', to='scout.player')),
                ('position_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineups_position_4', to='scout.player')),
                ('position_5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineups_position_5', to='scout.player')),
                ('position_6', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineups_position_6', to='scout.player')),
                ('set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='scout.set')),
            ],
        ),
    ]
