# Generated by Django 5.2.17 on 2026-10-07 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0008_lineup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_in', to='scout.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_out', to='scout.player')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='scout.set')),
            ],
        ),
    ]
