# Generated by Django 5.2.17 on 2026-10-07 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0009_substitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='current_position_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sets_position_1', to='scout.player'),
        ),
        migrations.AddField(
            model_name='set',
            name='current_position_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sets_position_2', to='scout.player'),
        ),
        migrations.AddField(
            model_name='set',
            name='current_position_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sets_position_3', to='scout.player'),
        ),
        migrations.AddField(
            model_name='set',
            name='current_position_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sets_position_4', to='scout.player'),
        ),
        migrations.AddField(
            model_name='set',
            name='current_position_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sets_position_5', to='scout.player'),
        ),
        migrations.AddField(
            model_name='set',
            name='current_position_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sets_position_6', to='scout.player'),
        ),
    ]
